name: Lint english prose

on: push

jobs:
  write-good:
    name: Write-good
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Write-good
        uses: '../actions/write-good-action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
